{% set name = "rubin-env" %}
{% set version = "2.0.0dev" %}
{% set build_number = 1 %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  skip: True  # [python_impl == 'pypy' or win or py != 311]
  number: {{ build_number }}

outputs:
  - name: rubin-env-nosysroot
    script: build-nosysroot.sh
    # Since all requirements are required "at run time" for the
    # Rubin developers, all requirements are fundamentally
    # run requirements. However, we've attempted to organize
    # requirements as build-like, host-like, or run-like, in
    # order inform any evolution of this recipe.
    requirements:
      host:
        - python
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - apr
        - cfitsio
        - curl
        - fftw
        - gsl
        - libaprutil
        - libblas
        - libcblas
        - liblapack
        - liblapacke
        - log4cxx
        - openblas
        - minuit2
        - numpy
        - starlink-ast
        - wcslib
        - xpa
      run_constrained:
        - impi_rt == 9999999999999
      run:
        # jq is special - it is needed for the pin-it utility in this package
        - jq >=1.7.1
        ###################################################
        # build-like dependencies
        # As part of our scons build process, we do run tests, so
        # these really are required to perform a build.
        # Note that "testing" in conda-forge should be limited to testing
        # successful packaging, and not testing code.
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        # The above are needed to get the official conda-forge versions.
        # The below is needed to get convenience symlinks for users to invoke.
        - compilers >=1.7.0
        - cmake >=3.28.1
        - coverage >=7.3.3
        - coveralls >=1.8.0
        - doxygen >=1.9.8
        - eups >=2.2.8
        - flake8 ==7.1.0
        - libblas * *openblas
        - openblas
        - make >=4.3
        - meson >=1.3.0
        - nose >=1.3.7
        - pep8-naming >=0.13.3
        - pip >=23.3.2
        - pkg-config >=0.29.2
        - psutil >=5.9.7
        - pytest >=8.2.0
        - pytest-cov >=4.1.0
        - pytest-doctestplus >=1.1.0
        - pytest-openfiles >=0.5.0
        - pytest-runner >=6.0.0
        - pytest-session2file >=0.1.11
        - pytest-subtests >=0.11.0
        - pytest-vcr >=1.0.2
        - pytest-xdist >=3.5.0
        - setuptools <=72.1.0
        - scons >=4.6.0

        ###################################################
        # host-like and run-like
        # These are mostly run-like, but for the same reasons as
        # above, we need most of these at build time, so they are mostly
        # host-like
        - boost =1.74
        - cfitsio =4
        - eigen =3.3
        - eups
        - firefly-client
        - galsim
        - libaprutil =1
        # there is some issue with pex_exceptions with clang 11 and libcxx 12
        # until it is tracked down, it makes sense to keep these at the same
        # major version
        - libcxx =={{ cxx_compiler_version }}.*  # [osx]
        - llvmlite
        - log4cxx {{ log4cxx }}.*
        - minuit2 {{ minuit2 }}.*
        - ndarray {{ ndarray }}.*
        - ndarray >=1.6.4
        - numba
        - numpy {{ numpy }}.*
        - starlink-ast {{ starlink_ast }}.*
        - wcslib {{ wcslib }}.*
        - xpa {{ xpa }}.*
        - yaml-cpp {{ yaml_cpp }}.*

        ###################################################
        # run-like
        - alembic >=1.13.0
        - astropy >=6.0.0,<6.1.5
        - astroquery >=0.4.6,<0.4.8
        - autograd >=1.6.2
        - backoff >=2.2.1
        - batoid >=0.7.3
        - batoid-rubin >=0.5.0
        - boto3 >=1.34.4
        - bottleneck >=1.3.7
        - cassandra-driver >=3.28.0  # [linux64]
        - click >=8.1.7
        - coloredlogs >=15.0.1
        - colour-science >=0.4.4
        # conda is required for runtime inspection of installed software
        - conda
        - configparser
        - cffi =1
        - click
        - coloredlogs
        - cython =0
        - deprecated
        - dustmaps
        - emcee
        - esutil
        - fastavro
        - future
        - git
        - git-lfs
        - gsl =2
        - h5py
        - healpy
        - healsparse
        - idds-client >=0.9.5
        - idds-doma >=0.9.5
        # inflection may go away in the future; see DM-32591
        - inflection
        - iminuit >=2
        - lmfit !=1.0.3
        - lsstdesc.coord
        - matplotlib-base
        - moto
        - mpi4py
        - ndarray =1
        - networkx
        - numexpr =2
        - numpy =1.21
        - pandas
        - pgcli
        - photutils >=0.7
        - piff
        - prmon  # [linux]
        - psycopg2 =2
        - pyarrow
        - pybind11
        - pydantic
        - pysynphot
        - pytables
        - python =3.10
        - pyyaml
        - requests
        - schwimmbad
        - scikit-image !=0.18
        - scikit-learn
        - scipy
        - seaborn
        - sqlalchemy <2
        - sqlite
        - tqdm
        - treecorr =4
        - ws4py

    test:
      commands:
        # grep pin-it output for python dependency
        - pin-it rubin-env-nosysroot | grep "python="
        # ensure binary compatibility; bump major version if not
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1017 ]'  # [linux]
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1002 ]'  # [osx]

  - name: rubin-env
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env-nosysroot", exact=True) }}
        - {{ stdlib("c") }}
        - python
    test:
      commands:
        # grep pin-it output for python dependency
        - pin-it rubin-env | grep "python="
        # ensure binary compatibility; bump major version if not
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1017 ]'  # [linux]
        - '[ $(echo __GXX_ABI_VERSION | ${CXX} -E - | tail -1) == 1002 ]'  # [osx]

  - name: rubin-env-rsp
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env", exact=True) }}
        # All are from sciplat-lab unless otherwise stated
        - astroplan >=0.10 # sims
        - astrowidgets >=0.3.0
        - awkward >=2.6.4
        - awkward-pandas >=2023.8.0
        - black >=24.0.0,<25.0.0
        - black-jupyter
        - bokeh >=3.3.2
        - bqplot >=0.12.43
        - ciso8601 >=2.3.1
        - cloudpickle >=3.0.0
        - cookiecutter >=2.6.0
        - dask-core >=2024.5.0,<2025.1.0  # Unpin once datashader 0.17.0
        - datashader >=0.16.0
        - fastparquet >=2024.2.0
        - ffmpeg >=4.4.0
        - freetype-py >=2.4.0
        - gcsfs >=2024.3.1
        - geoviews >=1.12.0
        - gh >=2.46.0  # 2.49.0 is not available on aarch64
        - ginga >=5.0.1
        - graphviz >=9.0.0
        - hatch-jupyter-builder >=0.9.1
        - hatch-nodejs-version >=0.3.2
        - hatchling >=1.24.2
        - hdf5plugin >=4.4.0
        - holoviews >=1.18.3
        - httpx >=0.27.0
        - hvplot >=0.9.0
        - imagemagick >=7.1.1_21
        - intake >=2.0.5
        - intake-parquet >=0.3.0
        - ipyevents >=2.0.2
        - ipykernel >=6.29.3
        - ipympl >=0.9.4
        - ipyvolume >=0.6.3
        - ipywidgets >=8.1.2
        - isort >=5.13.2
        - jedi >=0.19.1
        - jupyter >=1.0.0
        - jupyter-packaging >=0.12.3
        - jupyter-resource-usage >=1.0.2
        - jupyter-server-proxy >=4.1.2
        - jupyter_bokeh >=4.0.4
        - jupyterhub >=4.1.5
        - jupyterlab >=4.1.8,<5
        - jupyterlab-variableinspector >=3.2.1
        - jupyterlab_execute_time >=3.1.2
        - jupyterlab_iframe >=0.5.0
        - jupyterlab_widgets >=3.0.10
        - lsst-efd-client >=0.12.0
        - mypy >=1.7.1
        - mysqlclient >=2.2.1
        - nbconvert-webpdf >=7.7.1
        - nbdime >=4.0.1
        - nbval >=0.11.0
        - nodejs >=20.12.2
        - panel >=1.4.2
        - papermill >=2.6.0
        - paramnb >=2.0.4
        - partd >=1.4.1
        - pep8 >=1.7.1
        - plotly >=5.22.0
        - pre-commit >=3.6.0
        - pyflakes >=3.0.1
        - pypandoc >=1.13
        - pyshp >=2.3.1
        - python-snappy >=0.7.1
        - python-socketio >=5.11.2
        - pythreejs >=2.4.2
        - pyviz_comms >=3.0.1
        - pyvo >=1.5
        - regions >=0.9
        - ripgrep >=14.0.3
        - rubin-scheduler >=1.1.1
        - rubin-sim >=2.0.0
        - sbpy >=0.3.0
        - schedview >=0.11.1
        - sidecar >=0.7.0
        - snappy >=1.1.10
        - terminado >=0.18.1
        - toolz >=0.12.1
        - wget >=1.21.4
        - xarray >=2024.3.0
        - yarn >=4.2.1
    test:
      commands:
        # grep pin-it output for yarn dependency
        - pin-it rubin-env-rsp | grep "yarn="

  - name: rubin-env-developer
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env", exact=True) }}
        - astrowidgets >=0.3
        - black >=24.0.0,<25.0.0
        - bokeh >=3.3.2
        - clang-format >=18.0.0
        - dask-jobqueue >=0.8.5
        - datashader >=0.16.0
        - fastparquet >=2024.2.0
        - ffmpeg >=4.4.0
        - holoviews >=1.18.3
        - hvplot >=0.9.0
        - imagemagick >=7.1.1_21
        - ipdb >=0.13.13
        - ipympl >=0.9.4
        - ipython >=8.22.2
        - isort >=5.13.2
        - jedi >=0.19.1
        - jupyter >=1.0.0
        - jupyterlab >=4.1.8,<5
        - jupyterlab_server >=2.27.1
        - line_profiler >=4.1.1
        - lsst-documenteer-pipelines ==0.8.2
        - lsst-documenteer-technote ==0.8.2
        - lsst-efd-client >=0.12.0
        - mypy >=1.7.1
        - mysqlclient >=2.2.1
        - panel >=1.4.2
        - pep8 >=1.7.1
        - postgresql >=16.2
        - pre-commit >=3.6.0
        - pyct >=0.5.0
        - pydocstyle >=6.3.0
        - pyflakes >=3.0.1
        - pytest-profiling >=1.7.0
        - python-build >=1.2.1
        - pyvo >=1.5
        - ripgrep >=14.0.3
        - snakeviz >=2.2.0
        - sphinx-automodapi >=0.16.0,!=0.17.0
        - types-deprecated >=1.2.9.20240311
        - types-pkg_resources >=0.1.3
        - types-python-dateutil >=2.9.0.20240316
        - types-pyyaml >=6.0.12.20240311
        - types-requests >=2.31.0.6
        - types-setuptools >=69.5.0.20240423
        - types-urllib3 >=1.26.25.14
    test:
      commands:
        # grep pin-it output for black dependency
        - pin-it rubin-env-developer | grep "black"

  - name: rubin-env-extras
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage("rubin-env", exact=True) }}
        - {{ pin_subpackage("rubin-env-rsp", exact=True) }}
        - {{ pin_subpackage("rubin-env-developer", exact=True) }}
        - rubin-sim >=2.0.0
    test:
      commands:
        # grep pin-it output for rubin-env-developer dependency
        # Can't do rubin-sim due to lack of ARM
        - pin-it rubin-env-extras | grep "rubin-env-developer"

about:
  home: https://github.com/conda-forge/rubinenv-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Metapackage to install the Rubin Observatory's common software environment.

  description: |
    This metapackage exists to define the Rubin Observatory common software
    environment, including version specifications where needed, while allowing
    users flexibility when installing additional packages into the same environment.

extra:
  recipe-maintainers:
    - mwittgen
    - timj
    - ktlim
    - erykoff
    - beckermr
    - roceb
